# Generated by Django 4.2.23 on 2025-07-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('opponent_name', models.CharField(max_length=100)),
                ('opponent_logo', models.ImageField(blank=True, null=True, upload_to='opponent_logos/')),
                ('goals_for', models.PositiveIntegerField()),
                ('goals_against', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('T', 'Tie')], max_length=1)),
                ('attendees', models.ManyToManyField(related_name='attended_games', through='core.Attendance', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('game', 'player')},
        ),
    ]
